# Generated by Django 3.2.7 on 2021-09-08 07:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='lastUpdated',
            field=models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0)),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='numOfFollowers',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('stars', models.IntegerField(default=0)),
                ('profiles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myprofile.profiles')),
            ],
        ),
    ]
