# Generated by Django 3.2.7 on 2021-09-16 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0002_auto_20210908_1232'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repository',
            options={'ordering': ['-stars']},
        ),
    ]
