# Generated by Django 3.2.7 on 2021-09-16 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0003_alter_repository_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='lastUpdated',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 16, 16, 7, 14, 334039)),
        ),
    ]
