# Generated by Django 3.2.7 on 2021-09-16 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0004_alter_profiles_lastupdated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='lastUpdated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
