# Generated by Django 3.2.7 on 2021-09-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0005_alter_profiles_lastupdated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='lastUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
